version: "3"
services:
  sticks-db:
    image: postgres:13-alpine
    container_name: tg-features-container
    environment:
      POSTGRES_DB: "tg-features"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    env_file:
      - app.env
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sticks:
    container_name: sticks
    image: sticks-img
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: "app"
    env_file:
      - app.env
    environment:
      APP_JAR_PATH: ./StickKs-0.0.1.jar
      TDLIB_PATH: /app/td/tdlib/bin/libtdjni.so
    volumes:
      - "${HOME}/.m2/repository:/root/.m2/repository"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - sticks-db