version: "3"
services:
  sticks-db:
    image: postgres:13-alpine
    container_name: tg-features-container
    environment:
      POSTGRES_DB: "tg-features"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    env_file:
      - app.env
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sticks-net

  sticks:
    container_name: sticks
    image: sticks-img
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: "app"
    env_file:
      - app.env
    environment:
      TDLIB_PATH: "/app/libs/libtdjni.so"
      POSTGRES_DB: "tg-features"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      JDBC_URL: "jdbc:postgresql://sticks-db:5432/tg-features"
      R2DBC_URL: "r2dbc:postgresql://sticks-db:5432/tg-features"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - sticks-db
    networks:
      - sticks-net

networks:
  sticks-net: