version: "3"
services:
  sticks-db:
    image: mongo
    container_name: sticks-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "sticks"
    ports:
      - "27017:27017"

  sticks:
    container_name: sticks
    image: sticks-img
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: "app"
    volumes:
      - "${HOME}/.m2/repository:/root/.m2/repository"
    environment:
      MONGO_USER: "root"
      MONGO_PASS: "root"
      MONGO_DB: "sticks"
      MONGO_PORT: "27017"
      TDLIB_PATH: "/app/td/tdlib/bin/libtdjni.so"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - sticks-db