version: "3"
services:
  sticks-db:
    image: sticks-postgres-img
    container_name: sticks-db
    environment:
      POSTGRES_DB: "stickksdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data"

  sticks:
    image: sticks-img
    container_name: sticks
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - "${HOME}/.m2/repository:/root/.m2/repository"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://sticks-db:5432/stickksdb"
      APP_DIR: "/app"
      JAVA_LIBRARY_PATH: "./td/tdlib/bin"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - sticks-db