spring:
  application:
    name: StickKs
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  flyway:
    url: ${JDBC_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
  r2dbc:
    url: ${R2DBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  ai:
    deepseek:
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8

tdlib.config:
  use-message-database: true
  database-directory: tdlib
  use-secret-chats: true
  api-id: ${TDLIB_API_ID}
  api-hash: ${TDLIB_API_HASH}
  system-language-code: en
  device-model: Desktop
  application-version: 1.0
  log-verbosity-level: 0

logging:
  level:
    flyway: DEBUG

stickks:
  dsl-dependencies: "src/main/resources/dsl/dependencies"
  features:
    management:
      fetch-updates-strategy: DEFAULT